version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn django_web_rtc.wsgi:application --bind 0.0.0.0:8000
#    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/home/web/staticfiles
      - media_volume:/home/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env
#    depends_on:
#      - db
#  db:
#    image: postgres:12.0-alpine
#    volumes:
#      - postgres_data:/var/lib/posgresql/data/
#    env_file:
#      - ./.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/web/staticfiles
      - media_volume:/home/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: